home/urls.py
from django.urls import path
from home import views
from home.views import offline

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('offline/', offline, name='offline'),

]

myblog/urls.py
from django.urls import path
from . import views

app_name = 'myblog'

urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
]

myblog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='images', blank=True)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

myblog/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=TinyMCE())

    class Meta:
        model = Post
        fields = ('title', 'content', 'image')

myblog/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post


class PostList(ListView):
    queryset = Post.objects.filter().order_by('-created_date')
    template_name = 'myblog/post_list.html'


class PostDetailView(DetailView):
    model = Post
    template_name = 'myblog/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        # Get related posts based on similar content or title
        related_posts = Post.objects.filter(
            Q(content__icontains=post.content[:50]) |
            Q(title__icontains=post.title[:50])
        ).exclude(id=post.id)[:3]
        context['related_posts'] = related_posts
        return context

myblog/templates/myblog/post_detail.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="card bg-dark">
                    {% if post.image %}
                        <img class="card-img-top" src="{{ post.image.url }}" alt="{{ post.title }}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text">{{ post.content | safe }}</p>
                    </div>
                    <div class="card-footer text-muted">
                        نوشته شده در {{ post.created_date }}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-dark">پست های مرتبط</h5>
                        <hr>
                        {% for related_post in related_posts %}
                            <div class="border border-2 rounded-2 p-4">
                                <h6 class="card-subtitle mb-2 text-muted">{{ related_post.title }}</h6>
                                {% if post.image %}
                                    <img class="card-img-top" src="{{ related_post.image.url }}" alt="{{ post.title }}">
                                {% endif %}
                                <p class="card-text">{{ related_post.content|truncatechars:30 }}</p>
                                <a href="{% url 'myblog:post_detail' related_post.pk %}" class="btn btn-primary w-100">مشاهده
                                    پست</a>
                            </div>

                            <hr>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

myblog/templates/myblog/post_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Blog Posts</h1>
        <hr>
        <div class="row">
            {% for post in object_list %}
                <div class="col-md-4 mb-3">
                    <div class="card">
                        {% if post.image %}
                            <img class="card-img-top" src="{{ post.image.url }}" alt="{{ post.title }}">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title text-dark">{{ post.title }}</h5>

                            <a href="{% url 'myblog:post_detail' post.pk %}" class="btn btn-primary">مشاهده پست</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}