accounts/urls.py
from django.urls import path

from . import views
from .views import UserEditView

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('UserPriceChanges/', views.UserPriceChangesView.as_view(), name='user_price'),
    path('changes/<slug:slug>/', views.PriceChangesListView.as_view(), name='price_change'),
    path('edit-user/', UserEditView.as_view(), name='edit_user'),

]

home/urls.py
from django.urls import path
from home import views
from home.views import offline

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('offline/', offline, name='offline'),

]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser
from django.db import models

from shop.models import Product
from .managers import UserManager


class User(AbstractBaseUser):
    name = models.CharField(max_length=255)
    family = models.CharField(max_length=255)
    email = models.EmailField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=255, unique=True, db_index=True)
    age = models.PositiveIntegerField(null=True)
    register_date = models.DateTimeField(auto_now_add=True)
    card_number = models.CharField(max_length=200, unique=True, null=True, blank=True)
    address = models.TextField(max_length=1000)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    # every thing that added in username_field should be __ unique = true
    USERNAME_FIELD = 'phone_number'

    # every thing that added in required-fields only use in createsuperuser
    REQUIRED_FIELDS = ['email', 'name']

    def __str__(self):
        return self.name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    def full_name(self, name, family):
        full_name = f'{name} + " " + {family}'
        return full_name


class OtpCode(models.Model):
    phone_number = models.CharField(max_length=11, unique=True)
    code = models.PositiveSmallIntegerField()
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.phone_number} - {self.code} - {self.created}'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError

from .models import OtpCode
from .models import User


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='رمز عبور', widget=forms.PasswordInput)
    password2 = forms.CharField(label='تکرار رمز عبور', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('name', 'family', 'email', 'phone_number', 'age',
                  'card_number', 'address')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise ValidationError('کلمه عبور باید یکسان باشد')
        return cd['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(
        help_text='میتوانید از <a href=\"../password/\">این لینک</a> برای تغییر پسوورد استفاده کنید')

    class Meta:
        model = User
        fields = ('password', 'name', 'family', 'email', 'phone_number', 'age', 'card_number', 'address')


class UserRegistrationForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    family = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(max_length=11, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('این ایمیل از قبل وجود دارد')
        return email

    def clean_phone(self):
        phone = self.cleaned_data['phone_number']
        user = User.objects.filter(phone_number=phone).exists()
        if user:
            raise ValidationError('این شماره موبایل از قبل وجود دارد')
        OtpCode.objects.filter(phone_number=phone).delete()
        return phone


class VerifyCodeForm(forms.Form):
    code = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))


class UserLoginForm(forms.Form):
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name', 'family', 'email', 'phone_number', 'age', 'address', 'card_number']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'family': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control'}),
            'card_number': forms.TextInput(attrs={'class': 'form-control'}),
        }

accounts/views.py
import random

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import FloatField, ExpressionWrapper, F
from django.shortcuts import redirect, get_object_or_404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, UpdateView
from jalali_date import date2jalali

from shop.models import UserProduct, PriceChange, Product
from utils import send_otp_code
from .forms import UserRegistrationForm, VerifyCodeForm, UserLoginForm, UserEditForm
from .models import OtpCode, User


class UserRegisterView(View):
    form_class = UserRegistrationForm
    template_name = 'accounts/register.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            random_code = random.randint(1000, 9999)
            send_otp_code(form.cleaned_data['phone_number'], random_code)
            OtpCode.objects.create(
                phone_number=form.cleaned_data['phone_number'], code=random_code)
            request.session['user_registration_info'] = {
                'phone_number': form.cleaned_data['phone_number'],
                'email': form.cleaned_data['email'],
                'name': form.cleaned_data['name'],
                'family': form.cleaned_data['family'],
                'password': form.cleaned_data['password']
            }
            messages.success(request, 'کد تایید برای شما ارسال شد', 'success')
            return redirect('accounts:verify_code')
        return render(request, self.template_name, {'form': form})


class UserRegisterVerifyCodeView(View):
    form_class = VerifyCodeForm

    def get(self, request):
        form = self.form_class
        return render(request, 'accounts/verify.html', {'form': form})

    def post(self, request):
        user_session = request.session['user_registration_info']
        code_instance = OtpCode.objects.get(
            phone_number=user_session['phone_number'])
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['code'] == code_instance.code:
                User.objects.create_user(user_session['phone_number'], user_session['email'], user_session['name'],
                                         user_session['password'])
                code_instance.delete()
                messages.success(
                    request, 'ثبت نام با موفقیت انجام شد', 'success')
                return redirect('home:home')
            else:
                messages.error(request, 'کد وارد شده اشتباه است', 'danger')
                return redirect('accounts:verify_code')
        return render(request)


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request, phone_number=cd['phone_number'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'با موفقیت وارد شدید', 'success')
                return redirect('home:home')
            messages.error(
                request, 'شماره موبایل یا رمز عبور اشتباه است', 'danger')
        return render(request, self.template_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'با موفقیت خارج شدید', 'info')
        return redirect("home:home")


class UserPriceChangesView(LoginRequiredMixin, ListView):
    model = UserProduct
    template_name = 'accounts/user_price_changes.html'
    context_object_name = 'user_products'

    def get_queryset(self):
        return UserProduct.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_products = context['user_products']

        # Fetch all related price changes and products in a single query
        price_changes_queryset = PriceChange.objects.filter(
            product__userproduct__in=user_products
        ).select_related('product')

        price_changes_dict = {}
        product_price_data = {}
        all_dates = set()
        for price_change in price_changes_queryset:
            product = price_change.product
            if product not in price_changes_dict:
                price_changes_dict[product] = []

            price_changes_dict[product].append(price_change)
            date = price_change.created_at.date()
            all_dates.add(date)
            if product.name not in product_price_data:
                product_price_data[product.name] = []
            product_price_data[product.name].append(
                (date, price_change.new_price))

        # ... (Process the fetched data as before)

        return context
    model = UserProduct
    template_name = 'accounts/user_price_changes.html'
    context_object_name = 'user_products'

    def get_queryset(self):
        return UserProduct.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_products = context['user_products']
        price_changes = []
        sum_benefit = 0
        product_benefit = {}
        product_price_data = {}
        all_dates = set()
        User = get_user_model()
        user = get_object_or_404(User, pk=self.request.user.pk)
        for user_product in user_products:
            product = user_product.product
            product_price_changes = PriceChange.objects.filter(
                product=product).order_by('created_at')
            if product_price_changes:
                price_data = []
                initial_price = product_price_changes.first().new_price
                for price_change in product_price_changes:
                    date = price_change.created_at.date()
                    all_dates.add(date)
                    price_data.append((date, price_change.new_price))
                product_price_data[product.name] = price_data

                first_price = product_price_changes.first().new_price
                benefit = (product_price_changes.last().new_price -
                           user_product.initial_price) * user_product.quantity
                sum_benefit += benefit
                percentage_change = ((
                    product_price_changes.last().new_price - user_product.initial_price) / user_product.initial_price) * 100
                price_changes.append({
                    'product': product,
                    'current_price': product_price_changes.last().new_price,
                    'price_change': product_price_changes.last(),
                    'quantity': user_product.quantity,
                    'benefit': benefit,
                    'percentage_change': percentage_change,
                    'first_price': first_price,
                    'user_product': user_product
                })
                product_benefit[product.name] = {
                    'product': product, 'benefit': benefit}

        context['price_changes'] = price_changes
        context['num_products'] = sum([p['quantity'] for p in price_changes])
        context['sum_benefit'] = sum_benefit
        context['product_benefit'] = product_benefit
        context['wallet'] = user.wallet.balance

        # Prepare data for the line chart
        line_data = []
        for product_name, price_data in product_price_data.items():
            line_data.append({
                'label': product_name,
                'data': [(date.strftime('%Y-%m-%d'), price) for date, price in price_data],
                'fill': False
            })
        line_data = sorted(line_data, key=lambda x: x['label'])

        context['line_data'] = line_data
        context['all_dates'] = sorted(list(all_dates))

        # Prepare data for the bar chart
        bar_data = []
        for user_product in user_products:
            product_name = user_product.product.name
            initial_price = user_product.initial_price
            current_price = PriceChange.objects.filter(
                product=user_product.product).latest('created_at').new_price
            price_change = current_price - initial_price
            bar_data.append({
                'product_name': product_name,
                'initial_price': initial_price,
                'current_price': current_price,
                'price_change': price_change
            })
        bar_data = sorted(bar_data, key=lambda x: x['product_name'])

        context['bar_data'] = bar_data
        return context


class PriceChangesListView(View):
    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        price_changes = PriceChange.objects.filter(
            product=product).order_by('created_at')

        # Create lists for the chart data
        labels = []
        old_prices = []
        new_prices = []

        # Add data to the lists
        for price_change in price_changes:
            labels.append(date2jalali(
                price_change.created_at).strftime("%Y-%m-%d"))
            old_prices.append(price_change.old_price)
            new_prices.append(price_change.new_price)

        # Calculate the percent change for each price change
        percent_changes = ExpressionWrapper(

accounts/templates/accounts/edit_user.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Edit User</h1>
        <div class="row justify-content-center">
            <div class="col-5 bg-dark p-4 rounded-2">
                <form method="post">
                    {% csrf_token %}

                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary w-100">Save Changes</button>


                </form>
            </div>

        </div>

    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <h2 class="text-center">ورود</h2>
    <div class="container  col-md-6 border border-2 border-primary rounded text-bg-dark p-4 shadow-sm">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary col-12" type="submit" value="Login">
        </form>
    </div>



{% endblock %}

accounts/templates/accounts/price_changes_list.html
{% extends 'base.html' %}
{% load jalali_tags %}

{% block content %}
    <img class="card-img-top w-100 rounded-2 my-4" src="{{ product.image.url }}" height="500px">
    <div class="container my-5">

        <h1 class="text-secondary">جزيیات {{ product.name }}</h1>
        <hr>
        <div class="my-5 border border-2 border-primary rounded">
            <canvas id="price-chart" class="text-bg-dark"></canvas>
        </div>
        <div class="table-responsive border border-2 border-primary rounded shadow shadow-lg">
            <table class="table table-striped table-hover table-dark ">
                <thead>
                <tr>
                    <th>نام محصول</th>
                    <th>قیمت قبلی</th>
                    <th>قیمت جدید</th>
                    <th>تاریخ ایجاد</th>
                </tr>
                </thead>
                <tbody>
                {% for price_change in price_changes %}
                    <tr>
                        <td>{{ price_change.product.name }}</td>
                        <td>{{ price_change.old_price }} تومان</td>
                        <td>{{ price_change.new_price }} تومان</td>
                        <td>{{ price_change.created_at|to_jalali:'%y/%m/%d' }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4">هیچ تغییری وجود ندارد.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        var ctx = document.getElementById('price-chart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: [{% for label in labels %}"{{ label }}", {% endfor %}],
                datasets: [{
                    label: 'قیمت',
                    data: [{% for price in new_prices %}{{ price }}, {% endfor %}],
                    borderColor: 'rgb(89, 179, 49)',
                    backgroundColor: 'rgba(89, 179, 49, 0.2)',
                    fill: false,
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
    </script>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
    <h2 class="text-center">User Register</h2>
    <div class="container  col-md-6 border border-2 border-primary rounded text-bg-dark p-4 shadow-sm">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary col-12" type="submit" value="register">
        </form>
    </div>



{% endblock %}

accounts/templates/accounts/sell_product.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        <h1>Sell Product</h1>
        <p>Are you sure you want to sell "{{ user_product.product.name }}"?</p>
        <p><strong>Current Price:</strong> {{ user_product.price }}</p>
        <p><strong>Initial Price:</strong> {{ user_product.initial_price }}</p>
        <p><strong>Quantity:</strong> {{ user_product.quantity }}</p>

        <form method="POST">
            {% csrf_token %}
            <button class="btn btn-primary" type="submit">Sell Product</button>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/user_price_changes.html
{% extends 'base.html' %} {% load jalali_tags %} {% block content %}
<div class="container my-5">
  <div class="row justify-content-center mt-3">
    <div
      class="card text-white bg-warning bg-gradient col-sm-12 col-md-6 mb-3 bg-opacity-75"
    >
      <div class="card-header">کارت شما</div>
      <div class="card-body">
        <h5 class="card-title">نام : {{ user.name }}</h5>
        <h5 class="card-title">نام خانوادگی : {{ user.family }}</h5>
        <h5 class="card-title">شماره تلفن : {{ user.phone_number }}</h5>
        <h5 class="card-title">شماره کارت : {{ user.card_number }}</h5>
        <a href="{% url 'accounts:edit_user' %}" class="btn btn-dark w-100"
          >ویرایش مشخصات</a
        >
      </div>
    </div>
  </div>
  <hr />

  <div class="row gap-4 justify-content-center">
    <div
      class="col-sm-12 col-md-3 border border-2 border-primary rounded p-5 text-md-center"
      style="
        background-image: repeating-radial-gradient(
            circle at 0 0,
            transparent 0,
            #141414 14px
          ),
          repeating-linear-gradient(#444cf755, #444cf7);
      "
    >
      تعداد محصولات سبد شما : {{ num_products }}
    </div>
    <div
      class="col-sm-12 col-md-3 border border-2 border-primary rounded p-5 text-md-center"
      style="
        background-image: repeating-radial-gradient(
            circle at 0 0,
            transparent 0,
            #141414 14px
          ),
          repeating-linear-gradient(#444cf755, #444cf7);
      "
    >
      مجموع سود شما: {{ sum_benefit }}
    </div>
    <div
      class="col-sm-12 col-md-3 border border-2 border-primary rounded p-5 text-md-center"
      style="
        background-color: #141414;
        opacity: 1;
        background-image: repeating-radial-gradient(
            circle at 0 0,
            transparent 0,
            #141414 14px
          ),
          repeating-linear-gradient(#444cf755, #444cf7);
      "
    >
      تاریخ عضویت شما: {{ user.register_date |to_jalali:'%y/%m/%d' }}
    </div>
    <div
      class="col-sm-12 col-md-2 border border-2 border-primary rounded p-5 text-md-center align-middle"
      style="
        background-color: #141414;
        opacity: 1;
        background-image: repeating-radial-gradient(
            circle at 0 0,
            transparent 0,
            #141414 14px
          ),
          repeating-linear-gradient(#444cf755, #444cf7);
      "
    >
      موجودی : {{ wallet }}
    </div>
  </div>
  <div class="mt-4">
    {% if user_products %}
    <div
      class="table-responsive border border-2 border-primary bg-dark rounded mb-3"
    >
        <table class="table table-striped table-hover table-dark" dir="rtl">
            <thead>
            <tr>
                <th scope="col">نام سهم</th>
                <th scope="col">تعداد</th>
                <th scope="col">قیمت خرید شما</th>
                <th scope="col">آخرین قیمت</th>
                <th scope="col">سود</th>
                <th scope="col">درصد تغییرات قیمت</th>

            </tr>
            </thead>
            <tbody>
            {% for price_change in price_changes %}
          <tr>
            <td>
              <a href="{{ price_change.product.get_absolute_url }}"
                >{{ price_change.product.name }}</a
              >
            </td>
            <td>{{ price_change.quantity }}</td>
            <td>{{ price_change.user_product.initial_price }} تومان</td>
            <td>{{ price_change.price_change.new_price }} تومان</td>
            <td>{{ price_change.benefit }} تومان</td>
            <td>{{ price_change.percentage_change | floatformat:2 }}%</td>
            <td>
              <a
                href="{% url 'accounts:price_change' price_change.product.slug %}"
                >مشاهده تغییرات قیمت</a
              >
            </td>
              <td>
                  <button id="sell-{{ price_change.product.id }}" class="btn btn-danger"
                          onclick="sellProduct('{{ price_change.product.id }}')">فروش
                  </button>
              </td>

          </tr>
          {% endfor %}
        </tbody>
        <tfoot>
          <tr>
            <td><strong>مجموع:</strong></td>
            <td>{{ num_products }}</td>
            <td></td>
            <td></td>
            <td><strong>{{ sum_benefit }} تومان</strong></td>
            <td></td>
          </tr>
        </tfoot>
      </table>
    </div>
    {% endif %}

    <div class="row gap-4 justify-content-center gy-2 col-sm-12 w-100">
      {% if user_products %}
      <div
        class="border border-2 border-primary rounded shadow col-sm-12 col-md-4 bg-dark bg-gradient"
      >
        <canvas class="p-2" id="myChart"></canvas>
      </div>
      <div
        class="border border-2 border-primary rounded shadow col-sm-12 col-md-6 bg-dark bg-gradient"
      >
        <canvas class="p-2" id="barChart"></canvas>
      </div>
      {% endif %}
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var labels = [];
    var data = [];

    {% for product_name, benefit_data in product_benefit.items %}
        labels.push('{{ product_name }}');
        data.push({{ benefit_data.benefit }});
    {% endfor %}

    var chart = new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: labels,
            datasets: [{
                label: 'سود',
                data: data,
                backgroundColor: [
                    'rgb(255, 99, 132)',
                    'rgb(54, 162, 235)',
                    'rgb(255, 205, 86)'
                ],
                hoverOffset: 5
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
  </script>

  <script>
    var barData = {
        labels: [
            {% for data in bar_data %}
                "{{ data.product_name }}",
            {% endfor %}
        ],
        datasets: [
            {
                label: "قیمت خرید شما",
                backgroundColor: "rgba(255,99,132,0.8)",
                borderColor: "rgba(255,99,132,1)",
                borderWidth: 1,
                hoverBackgroundColor: "rgba(255,99,132,0.4)",
                hoverBorderColor: "rgba(255,99,132,1)",
                data: [
                    {% for data in bar_data %}
                        {{ data.initial_price }},
                    {% endfor %}
                ],
            },
            {
                label: "آخرین قیمت",
                backgroundColor: "rgba(54, 162, 235, 0.7)",
                borderColor: "rgba(54, 162, 235, 1)",
                borderWidth: 1,
                hoverBackgroundColor: "rgba(54, 162, 235, 0.4)",
                hoverBorderColor: "rgba(54, 162, 235, 1)",
                data: [
                    {% for data in bar_data %}
                        {{ data.current_price }},
                    {% endfor %}
                ],
            },
            {
                label: "تغییرات قیمت",
                backgroundColor: "rgba(255, 206, 86, 0.8)",
                borderColor: "rgba(255, 206, 86, 1)",
                borderWidth: 1,
                hoverBackgroundColor: "rgba(255, 206, 86, 0.4)",
                hoverBorderColor: "rgba(255, 206, 86, 1)",
                data: [
                    {% for data in bar_data %}
                        {{ data.price_change }},
                    {% endfor %}
                ],
            },
        ],
    };
    var barOptions = {
        responsive: true,
        legend: {
            position: 'top',
        },
        title: {
            display: true,
            text: 'Bar Chart'
        },
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    };
    var barChart = new Chart(document.getElementById("barChart"), {
        type: 'bar',
        data: barData,
        options: barOptions
    });
  </script>
    <script>
        function sellProduct(productId) {
            if (confirm('آیا مطمئن هستید که می‌خواهید این محصول را بفروشید؟')) {
                const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
                fetch(`/accounts/sell_product/${productId}/`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrfToken,
                    },
                    body: JSON.stringify({
                        product_id: productId
                    })
                })
                    .then(response => {
                        if (response.ok) {
                            location.reload();
                        } else {
                            alert('فروش محصول با خطا مواجه شد. لطفاً دوباره تلاش کنید.');
                        }
                    })
                    .catch(error => {
                        console.error('Error:', error);
                        alert('فروش محصول با خطا مواجه شد. لطفاً دوباره تلاش کنید.');
                    });
            }
        }
    </script>

</div>

{% endblock %}

accounts/templates/accounts/verify.html
{% extends 'base.html' %}

{% block content %}
    <h2 class="text-center">ثبت نام</h2>
    <div class="container  col-md-6 border border-2 border-primary rounded text-bg-dark p-4 shadow-sm">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary col-12" type="submit" value="ثبت">
        </form>
    </div>



{% endblock %}