accounts/urls.py
from django.urls import path

from . import views
from .views import UserEditView

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('UserPriceChanges/', views.UserPriceChangesView.as_view(), name='user_price'),
    path('changes/<slug:slug>/', views.PriceChangesListView.as_view(), name='price_change'),
    path('edit-user/', UserEditView.as_view(), name='edit_user'),

]

home/urls.py
from django.urls import path
from home import views
from home.views import offline

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('offline/', offline, name='offline'),

]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <div class="container">
            <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
        </div>

    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-dark navbar-expand-lg bg-dark mb-3">

    <div class="container">
        <a class="navbar-brand text-primary" href="#">پلتفرم سهامداران</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">خانه</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href='{% url 'accounts:user_price' %}'>داشبورد</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href='{% url 'accounts:user_logout' %}'>خروج</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href='{% url 'accounts:user_register' %}'>ثبت نام</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href='{% url 'accounts:user_login' %}'>ورود</a>
                    </li>
                {% endif %}


            </ul>

        </div>
    </div>
</nav>